### ISSUE TITLE
Ending games crash with GameLogicException

### ISSUE THREAD

**Issue by anarchuser** [CAU-Kiel-Tech-Inf/gui#9]
Stack trace:
```
sc.api.plugins.exceptions.GameLogicException: Trying to access the currently active color with invalid index
	at sc.plugin2021.GameState.getCurrentColor(GameState.kt:69)
	at sc.gui.controller.GameController$1.invoke(GameController.kt:183)
	at sc.gui.controller.GameController$1.invoke(GameController.kt:133)
	at tornadofx.FXEventRegistration$action$1.invoke(EventBus.kt:42)
	at tornadofx.FXEventRegistration$action$1.invoke(EventBus.kt:33)
	at tornadofx.EventBus$fire$1.invoke(EventBus.kt:126)
	at tornadofx.EventBus$fire$3.run(EventBus.kt:147)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at javafx.graphics/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
	at javafx.graphics/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

On a game ending, it seems the currently active color of the latest game state is being accessed which does not hold any value (since no colors are left in the game, hence no color can be active).

Upon closer examination, the error seemed to be thrown immediately upon placement of the last piece, suggesting the issue is on processing the last move request or failing to properly halt the game with an onGameOver event directly afterwards

**Comment by SKoschnicke** [comment]
@anarchuser This is fixed, right?

**Comment by anarchuser** [comment]
I think so, yes.
Accessing the currently active color after game over will still throw (which is intended).
Thus, if we happen to get that error at some point, someone is probably accessing it unreasonably.
